feat: set pre-release automaticly

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,48 +1,88 @@
-#Workflow that creates a new package on any new release or when manually triggered
-name: release library package
+name: Release lib-version Maven package
+
 on:
-  #Manually create a release package
-  # workflow_dispatch:
   push:
-    tags:
-      # - v[0-9]+.[0-9]+.[0-9]+
-      - package
+    branches:
+      - main
+    paths:
+      - "pom.xml"
+  workflow_dispatch:
+
+permissions:
+  contents: write
+  packages: write
+
+env:
+  REGISTRY: ghcr.io
+  IMAGE_NAME: doda2025-team22/app
+  BUILD_ID: latest
+  MAVEN_USERNAME: ${{ github.actor }}
+  MAVEN_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
 
 jobs:
   build_package:
     runs-on: ubuntu-latest
-    permissions:
-      packages: write
-      contents: read
     steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
-
-      - name: Parse provided version tag
-        # Parse the input version tag (from the tag push) and store it in an environment variable
-        run: |
-          # Removes the v in the ref name == vX.Y.Z
-          VERSION="${GITHUB_REF_NAME#v}"
-          echo "VERSION=$VERSION" >> $GITHUB_ENV
+      - name: Checkout
+        uses: actions/checkout@v5
 
       - name: Setup JDK 25 # Java -v >= 25.0.1
         uses: actions/setup-java@v4 # Creates a settings.xml
         with:
           java-version: "25"
           distribution: "temurin"
-          cache: "maven"
-          server-id: doda-team22_libversion # Value of the distributionManagement id field of the pom.xml
-          settings-path: ${{ github.workspace }} # location for the settings.xml file
+          server-id: "github" # must match <id> in distributionManagement
+          server-username: MAVEN_USERNAME # env var names, not values
+          server-password: MAVEN_PASSWORD
 
-      - name: Set the Maven Version
+      - name: Determine version
         run: |
-          mvn versions:set -DnewVersion=$VERSION #or mvn -Drevision=$VERSION clean package https://maven.apache.org/guides/mini/guide-maven-ci-friendly.html
-          mvn versions:commit
+          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
+          echo "VERSION=$VERSION" >> $GITHUB_ENV
 
-      - name: Build Maven Package
-        run: mvn --batch-mode package --file pom.xml
+      - name: Check if snapshot
+        run: |
+          if [[ "${{ env.VERSION }}" != *"-SNAPSHOT"* ]]; then
+            echo "::error::Release version should contain -SNAPSHOT"
+            exit 1
+          else
+            echo "Release version is correct (contains -SNAPSHOT)"
+          fi
+  bump_version:
+    runs-on: ubuntu-latest
+    needs: build_package
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v5
 
-      - name: publish the package to github packages
-        run: mvn deploy --settings ${{ github.workspace }}/settings.xml
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - name: Setup JDK 25 # Java -v >= 25.0.1
+        uses: actions/setup-java@v4 # Creates a settings.xml
+        with:
+          java-version: "25"
+          distribution: "temurin"
+          server-id: "github" # must match <id> in distributionManagement
+          server-username: MAVEN_USERNAME # env var names, not values
+          server-password: MAVEN_PASSWORD
+
+      - name: Remove snapshot
+        run: |
+          mvn versions:set versions:commit -DremoveSnapshot -q
+          RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
+          echo "VERSION=${RELEASE_VERSION}" >> $GITHUB_ENV
+
+      - name: Build & deploy
+        run: mvn -B deploy
+
+      - name: Bump version
+        run: |
+          mvn release:update-versions --batch-mode
+          PRERELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
+
+      - name: Create commit
+        run: |
+          git config --global user.name "${{ github.actor }}"
+          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
+
+          git add pom.xml
+          git commit -m "Bump version to ${PRERELEASE_VERSION} [skip ci]"
+          git push
